# Generated by Django 5.2.2 on 2025-06-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnderConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_construction', models.BooleanField(default=False)),
                ('uc_note', models.TextField(blank=True, help_text='Note for under construction mode.', null=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
