# Generated by Django 5.2.2 on 2025-06-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='underconstruction',
            name='uc_duration',
            field=models.DateTimeField(blank=True, help_text='End date and time for under construction node.', null=True),
        ),
    ]
