# Generated by Django 5.2.1 on 2025-05-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='bksc', max_length=70),
            preserve_default=False,
        ),
    ]
