# Generated by Django 5.2.1 on 2025-05-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_name',
            field=models.CharField(default='Default Teacher', max_length=255),
        ),
    ]
