# Generated by Django 5.2.1 on 2025-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_user_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teacher_name',
            field=models.CharField(max_length=255),
        ),
    ]
