# Generated by Django 5.2.3 on 2025-06-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_discountedproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountedproduct',
            options={'ordering': ['id']},
        ),
    ]
